import React,{useState,useRef,useEffect,createContext,useContext} from 'react';import {createRoot} from 'react-dom/client';import axios from 'axios';import './index.css';
import {FiCamera,FiLock,FiLogOut,FiUserPlus,FiBell,FiX,FiHome,FiList,FiUser,FiCheckCircle,FiShield,FiWifi} from 'react-icons/fi';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,Legend,BarChart,Bar} from 'recharts';
const API_BASE_URL=(import.meta.env.VITE_API_URL||(import.meta.env.PROD?'https://attendance-rmb0.onrender.com/api':'/api')).replace(/\/$/,'');
const api=axios.create({baseURL:API_BASE_URL});api.interceptors.request.use(c=>{if(localStorage.token)c.headers.Authorization='Bearer '+localStorage.token;return c});
api.interceptors.response.use(r=>r,async e=>{const c=e.config;if(e.response?.status===401&&!c._r&&localStorage.refresh&&!c.url.includes('/auth/')){c._r=1;try{const{data}=await axios.post(API_BASE_URL+'/auth/refresh',{refresh:localStorage.refresh});localStorage.token=data.token;return api(c)}catch{localStorage.clear();location.reload()}}return Promise.reject(e)});
const err=e=>e.response?.data?.message||e.response?.data?.error||e.message;
const Brand=createContext();const out=()=>{localStorage.clear();location.reload()};
const tm=x=>x?new Date(x).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}):'—';
const hm=m=>`${String(m/60|0).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,mn=v=>+v.split(':')[0]*60+ +v.split(':')[1];
const iso=n=>new Date(Date.now()-n*864e5+19800000).toISOString().slice(0,10);
const col=r=>r.status==='Half Day'?'text-blue-600':r.lateMin>0||['Leave','Absent'].includes(r.status)?'text-red-600':r.status==='Holiday'?'text-gray-500':'text-green-600';
const Logo=({c=''})=>{const l=useContext(Brand);return l?<img src={l} className={'h-10 object-contain '+c}/>:<span className={'font-bold text-brand text-xl '+c}>Growthora</span>};
const Modal=({t,x,children})=><div className="fixed inset-0 bg-black/40 grid place-items-end md:place-items-center z-50" onClick={x}><div onClick={e=>e.stopPropagation()} className="bg-white rounded-t-2xl md:rounded-2xl p-4 w-full max-w-lg max-h-[90vh] overflow-auto space-y-2 pb-[env(safe-area-inset-bottom)]"><div className="flex justify-between"><h3 className="font-semibold text-lg">{t}</h3><button onClick={x}><FiX/></button></div>{children}</div></div>;
function Cam({onShot,label,live}){const v=useRef(),[h,setH]=useState(''),[b,setB]=useState(false);useEffect(()=>{let s;navigator.mediaDevices.getUserMedia({video:{facingMode:'user'}}).then(x=>{s=x;v.current.srcObject=x});return()=>s?.getTracks().forEach(t=>t.stop())},[]);
 const shot=()=>{const c=document.createElement('canvas');c.width=v.current.videoWidth;c.height=v.current.videoHeight;c.getContext('2d').drawImage(v.current,0,0);return c.toDataURL('image/jpeg',.85)};
 const go=async()=>{if(!live)return onShot(shot());setB(true);const fr=[];for(let i=0;i<9;i++){setH(i<3?'Look straight':i<6?'Slowly turn head to one side':'Now turn to the other side');fr.push(shot());await new Promise(r=>setTimeout(r,450))}setH('Verifying...');onShot(fr)};
 return <div><video ref={v} autoPlay playsInline muted className="w-full rounded-2xl bg-black"/>{h&&<p className="text-center font-semibold text-brand mt-2">{h}</p>}<button disabled={b} className="btn w-full mt-3" onClick={go}><FiCamera/>{label}</button></div>}
const Stat=({a,b,c='text-brand',onClick})=><div onClick={onClick} className={'card '+(onClick?'cursor-pointer':'')}><p className="text-xs text-gray-500">{a}</p><p className={'text-2xl font-bold '+c}>{b}</p></div>;
function Landing({go}){return <div className="min-h-screen flex flex-col"><header className="p-4 flex justify-between items-center"><Logo/><button className="btn" onClick={go}>Login</button></header>
 <main className="flex-1 max-w-4xl mx-auto p-6 text-center space-y-8"><h1 className="text-3xl md:text-5xl font-bold mt-10">Attendance that <span className="text-brand">knows it's you</span></h1><p className="text-gray-500">Face-verified check-in and check-out for the Growthora team, with live insights for admins.</p>
 <button className="btn mx-auto" onClick={go}>Login to continue</button><div className="grid md:grid-cols-3 gap-3 text-left">{[[FiShield,'Face + liveness','ArcFace matching with a head-turn liveness check'],[FiWifi,'Office-only','Attendance works only from the office network'],[FiCheckCircle,'Clear reports','Late, half-day and leave tracking in one place']].map(([I,a,b])=><div key={a} className="card"><I className="text-brand text-2xl"/><p className="font-semibold mt-2">{a}</p><p className="text-sm text-gray-500">{b}</p></div>)}</div></main>
 <footer className="p-4 text-center text-xs text-gray-500">Growthora Advisory Private Limited – Bengaluru. For any issue contact +91 6360886843</footer></div>}
function Login({set}){const[f,setF]=useState({email:'',password:''}),[m,setM]=useState('');
 const go=async()=>{try{const{data}=await api.post('/auth/login',f);localStorage.token=data.token;localStorage.refresh=data.refresh;localStorage.user=JSON.stringify(data.user);set(data.user)}catch(e){setM(err(e))}};
 return <div className="min-h-screen grid place-items-center p-4"><div className="card w-full max-w-sm space-y-3"><Logo/><input className="inp" placeholder="Email" onChange={e=>setF({...f,email:e.target.value})}/><input className="inp" type="password" placeholder="Password" onChange={e=>setF({...f,password:e.target.value})}/>{m&&<p className="text-red-600 text-sm">{m}</p>}<button className="btn w-full" onClick={go}>Login</button></div></div>}
function Pwd(){const[p,setP]=useState(''),[m,setM]=useState('');return <div className="card space-y-2"><h3 className="font-semibold">Change password</h3><input className="inp" type="password" placeholder="New password (min 8)" onChange={e=>setP(e.target.value)}/><button className="btn w-full" disabled={p.length<8} onClick={async()=>{try{await api.post('/auth/password',{password:p});setM('Password updated')}catch(e){setM(err(e))}}}>Update</button>{m&&<p className="text-sm">{m}</p>}</div>}
function Hist({id,admin}){const[d,setD]=useState(null),[r,setR]=useState({from:iso(30),to:iso(0)});
 const load=()=>api.get(id?`/employees/${id}/history`:'/attendance/history',{params:r}).then(x=>setD(x.data));useEffect(()=>{load()},[r.from,r.to]);
 const upd=async(a,body)=>{await a;load()};
 return <div className="space-y-3"><div className="flex gap-2"><input type="date" className="inp" value={r.from} onChange={e=>setR({...r,from:e.target.value})}/><input type="date" className="inp" value={r.to} onChange={e=>setR({...r,to:e.target.value})}/></div>
 {d&&<><div className="grid grid-cols-3 gap-2">{[['Present',d.st.present,'text-green-600'],['Half days',d.st.half,'text-blue-600'],['Leaves',d.st.leave,'text-red-600'],['Absent',d.st.absent,'text-red-600'],['Late',d.st.late,'text-red-600']].map(([a,b,c])=><Stat key={a} a={a} b={b} c={c}/>)}</div>
 {d.rows.map(x=><div key={x.date} className="card text-sm flex justify-between items-center gap-2"><div><b>{x.date}</b><p className={col(x)}>{x.status}</p></div><div className="text-right"><p className={x.lateMin>0?'text-red-600':'text-green-600'}>In {tm(x.checkIn)}</p><p>Out {tm(x.checkOut)} {x.hours!=null&&`· ${x.hours}h`}</p></div>
 {admin&&<div className="flex flex-col gap-1">{x._id&&<button className="text-brand text-xs" onClick={()=>upd(api.patch('/attendance/'+x._id,{status:x.status==='Half Day'?'Present':'Half Day'}))}>{x.status==='Half Day'?'→ Full':'→ Half'}</button>}{x.status==='Holiday'?<button className="text-brand text-xs" onClick={()=>upd(api.delete('/holidays/'+x.date))}>Remove holiday</button>:<button className="text-brand text-xs" onClick={()=>upd(api.post('/holidays',{date:x.date}))}>Holiday</button>}</div>}</div>)}</>}</div>}
function Employee({u}){const[tab,setTab]=useState('take'),[cam,setCam]=useState(null),[msg,setMsg]=useState(''),[today,setT]=useState([]);
 const load=()=>api.get('/attendance/history',{params:{from:iso(0),to:iso(0)}}).then(r=>setT(r.data.rows));useEffect(()=>{load()},[]);
 const send=async frames=>{try{const{data}=await api.post('/attendance/'+cam,{frames});setMsg((cam==='checkin'?'Your morning attendance is done':'Your logout attendance is done')+' at '+tm(data.at));setCam(null);load()}catch(e){setMsg(err(e));setCam(null)}};
 const locked=new Date(Date.now()+19800000).getUTCHours()<13,t=today[0];
 return <div className="max-w-md mx-auto p-4 pb-24 space-y-4"><Logo/>
 {tab==='take'&&<><h2 className="text-2xl font-bold">Welcome, {u.name}</h2><p className="text-gray-500">{u.designation}</p>
 {cam?<Cam live onShot={send} label="Start face check"/>:<><button className="btn w-full" onClick={()=>setCam('checkin')}><FiCamera/>Take Attendance</button><button className="btn w-full" disabled={locked} onClick={()=>setCam('checkout')}>{locked?<FiLock/>:<FiCamera/>}Logout Attendance</button></>}
 {msg&&<div className={'card '+(msg.includes('done')?'text-green-700':'text-red-600')}>{msg}</div>}{t&&<div className="card text-sm">Today: In {tm(t.checkIn)} · Out {tm(t.checkOut)}</div>}</>}
 {tab==='my'&&<Hist/>}{tab==='me'&&<><div className="card"><b>{u.name}</b><p className="text-sm text-gray-500">{u.designation}</p></div><Pwd/><button className="text-brand flex gap-1 items-center" onClick={out}><FiLogOut/>Logout</button></>}
 <nav className="fixed bottom-0 inset-x-0 bg-white border-t flex pb-[env(safe-area-inset-bottom)]">{[['take',FiHome,'Attendance'],['my',FiList,'History'],['me',FiUser,'Profile']].map(([k,I,l])=><button key={k} onClick={()=>setTab(k)} className={'flex-1 h-14 flex flex-col items-center justify-center text-xs '+(tab===k?'text-brand':'text-gray-500')}><I className="text-xl"/>{l}</button>)}</nav></div>}
function Settings(){const[c,setC]=useState(null),[m,setM]=useState('');useEffect(()=>{api.get('/settings').then(r=>setC(r.data))},[]);if(!c)return null;
 const set=(k,v)=>setC({...c,[k]:v}),T=(k,l)=><label className="text-sm">{l}<input type="time" className="inp" value={hm(c[k])} onChange={e=>set(k,mn(e.target.value))}/></label>;
 const save=async()=>{try{await api.put('/settings',{cutoff:c.cutoff,checkoutFrom:c.checkoutFrom,halfAfter:c.halfAfter,halfOutBefore:c.halfOutBefore,threshold:+c.threshold,ips:c.ips,logo:c.logo});setM('Saved. Reload to see new logo.')}catch(e){setM(err(e))}};
 const up=e=>{const f=e.target.files[0],r=new FileReader();r.onload=()=>set('logo',r.result);f&&r.readAsDataURL(f)};
 return <div className="space-y-3"><div className="card grid grid-cols-2 gap-3">{T('cutoff','Late after')}{T('checkoutFrom','Checkout unlocks')}{T('halfAfter','Half day if check-in after')}{T('halfOutBefore','Half day if out before')}
 <label className="text-sm col-span-2">Face match threshold (0.3–0.7)<input className="inp" type="number" step="0.01" value={c.threshold} onChange={e=>set('threshold',e.target.value)}/></label>
 <label className="text-sm col-span-2">Allowed office IPs / CIDR (comma separated)<input className="inp" value={(c.ips||[]).join(',')} onChange={e=>set('ips',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label>
 <label className="text-sm col-span-2">Company logo<input type="file" accept="image/*" onChange={up}/></label>{c.logo&&<img src={c.logo} className="h-12"/>}
 <button className="btn col-span-2" onClick={save}>Save settings</button>{m&&<p className="text-sm col-span-2">{m}</p>}</div><Pwd/></div>}
function Admin(){const[tab,setTab]=useState('dash'),[s,setS]=useState(null),[emps,setE]=useState([]),[rg,setRg]=useState({from:iso(0),to:iso(0)}),[reg,setReg]=useState(false),[shots,setShots]=useState([]),[f,setF]=useState({}),[m,setM]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[mod,setMod]=useState(null),[ns,setNs]=useState([]),[bell,setBell]=useState(false),[q,setQ]=useState('');
 const load=()=>{api.get('/attendance/summary',{params:rg}).then(r=>setS(r.data));api.get('/employees').then(r=>setE(r.data))};useEffect(load,[rg.from,rg.to]);
 useEffect(()=>{const es=new EventSource(API_BASE_URL+'/notifications/stream?t='+localStorage.token);es.onmessage=e=>{setNs(n=>[JSON.parse(e.data),...n]);load()};return()=>es.close()},[]);
 const save=async()=>{if(saving)return;setSaving(true);setM('');setNotice('');try{const{data}=await api.post('/employees',{...f,images:shots});setReg(false);setShots([]);setF({});setM('');setNotice(`Employee registered with ${data.acceptedPhotos} valid photos.${data.rejectedPhotos?.length?` Skipped: ${data.rejectedPhotos.join('; ')}`:''}`);load()}catch(e){const data=e.response?.data;setM(data?.rejectedPhotos?.join('; ')||err(e))}finally{setSaving(false)}};
 const steps=['Look straight at the camera','Turn just a little left; keep both eyes visible','Turn just a little right; keep both eyes visible','Look straight with a gentle smile','Look straight at the camera again'];
 const P=[[0,0,'Today'],[1,1,'Yesterday'],[6,0,'7 days'],[29,0,'30 days']];
 const cards=s&&[['Employees',s.total],['Present',s.present],['On time',s.onTime.length,'text-green-600',()=>setMod('on')],['Late',s.late.length,'text-red-600',()=>setMod('late')],['Half day',s.half,'text-blue-600'],['Absent (approx)',s.absent,'text-red-600'],['Checked in now',s.checkedIn],['Attendance %',s.pct+'%'],['Avg check-in',s.avg?hm(s.avg):'—'],['Holiday today',s.holiday?'Yes':'No'],['Top late comer',s.topLate[0]?.name||'—','text-red-600',()=>setMod('top')]];
 return <div className="max-w-5xl mx-auto p-4 space-y-4"><div className="flex justify-between items-center"><Logo/><div className="flex gap-3 items-center relative"><button onClick={()=>setBell(!bell)} className="relative"><FiBell className="text-xl"/>{ns.length>0&&<span className="absolute -top-2 -right-2 bg-brand text-white text-xs rounded-full px-1">{ns.length}</span>}</button>
 {bell&&<div className="card absolute right-0 top-8 w-64 z-40 text-sm">{ns.length?ns.map((n,i)=><p key={i}>{n.name} checked in {n.late} min late</p>):'No alerts'}</div>}<button onClick={out}><FiLogOut/></button></div></div>{notice&&<p className="text-sm text-green-700" role="status">{notice}</p>}
 <div className="flex gap-2 overflow-x-auto">{[['dash','Dashboard'],['emp','Employees'],['set','Settings']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={'px-4 h-11 rounded-xl whitespace-nowrap '+(tab===k?'bg-brand text-white':'bg-white')}>{l}</button>)}</div>
 {tab==='dash'&&<><div className="flex gap-2 flex-wrap items-center">{P.map(([a,b,l])=><button key={l} onClick={()=>setRg({from:iso(a),to:iso(b)})} className="px-4 h-11 rounded-xl bg-white">{l}</button>)}<input type="date" className="inp w-auto" value={rg.from} onChange={e=>setRg({...rg,from:e.target.value})}/><input type="date" className="inp w-auto" value={rg.to} onChange={e=>setRg({...rg,to:e.target.value})}/></div>
 {s&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{cards.map(([a,b,c,o])=><Stat key={a} a={a} b={b} c={c} onClick={o}/>)}</div>
 <div className="grid md:grid-cols-2 gap-3"><div className="card h-64"><ResponsiveContainer><LineChart data={s.daily}><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Line dataKey="onTime" stroke="#16a34a" name="On time"/><Line dataKey="late" stroke="#B3122F" name="Late"/></LineChart></ResponsiveContainer></div>
 <div className="card h-64"><ResponsiveContainer><BarChart data={[{n:'On time',v:s.onTime.length},{n:'Late',v:s.late.length}]}><XAxis dataKey="n"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="v" fill="#B3122F"/></BarChart></ResponsiveContainer></div></div></>}</>}
 {tab==='emp'&&<div className="space-y-2"><input className="inp" placeholder="Search employees" onChange={e=>setQ(e.target.value.toLowerCase())}/><button className="btn" onClick={()=>setReg(true)}><FiUserPlus/>Register employee</button>
 {emps.filter(e=>(e.name+e.email).toLowerCase().includes(q)).map(e=><div key={e._id} className="card flex justify-between items-center"><button className="text-left" onClick={()=>setMod(e)}><b>{e.name}</b><p className="text-xs text-gray-500">{e.designation}</p></button><button className="text-brand text-sm" onClick={async()=>{await api.patch(`/employees/${e._id}/toggle`);load()}}>{e.enabled?'Disable login':'Enable login'}</button></div>)}</div>}
 {tab==='set'&&<Settings/>}
 {mod==='on'&&<Modal t={`On time (${s.onTime.length})`} x={()=>setMod(null)}>{s.onTime.map(r=><p key={r._id} className="text-sm text-green-600">{r.user?.name} – {tm(r.checkIn)}</p>)}</Modal>}
 {mod==='late'&&<Modal t={`Late (${s.late.length})`} x={()=>setMod(null)}>{s.late.map(r=><p key={r._id} className="text-sm text-red-600">{r.user?.name} – {tm(r.checkIn)} · {r.lateMin} min late</p>)}</Modal>}
 {mod==='top'&&<Modal t="Top late comers" x={()=>setMod(null)}>{s.topLate.map((t,i)=><p key={t.name} className="text-sm">{i+1}. {t.name}: {t.days} late days, avg {t.avg} min</p>)}</Modal>}
 {mod?._id&&<Modal t={mod.name} x={()=>setMod(null)}><Hist id={mod._id} admin/></Modal>}
 {reg&&<Modal t="Register employee" x={()=>{if(!saving)setReg(false)}}>{['name','designation','phone','email','password'].map(k=><input key={k} className="inp" placeholder={k==='password'?'Password (default Growthora2026)':k} onChange={e=>setF({...f,[k]:e.target.value})}/>)}
 {shots.length<5&&<><p className="text-sm">Photo {shots.length+1}/5: {steps[shots.length]}</p><Cam label="Capture" onShot={x=>setShots([...shots,x])}/></>}{shots.length>0&&<div className="flex flex-wrap gap-2 text-sm">{shots.map((_,i)=><button key={i} type="button" disabled={saving} className="text-brand underline disabled:opacity-50" title={`Remove photo ${i+1} to retake it`} onClick={()=>setShots(shots.filter((_,j)=>j!==i))}>Remove photo {i+1}</button>)}</div>}{m&&<p className="text-red-600 text-sm">{m}</p>}<button className="btn w-full" disabled={shots.length<3||saving} onClick={save}>{saving?'Registering...':'Register'}</button></Modal>}</div>}
function App(){const[u,setU]=useState(localStorage.user&&JSON.parse(localStorage.user)),[v,setV]=useState('land'),[logo,setL]=useState(null);useEffect(()=>{api.get('/public').then(r=>setL(r.data.logo)).catch(()=>{})},[]);
 return <Brand.Provider value={logo}>{u?u.role==='admin'?<Admin/>:<Employee u={u}/>:v==='land'?<Landing go={()=>setV('login')}/>:<Login set={setU}/>}</Brand.Provider>}
createRoot(document.getElementById('root')).render(<App/>);
